feat: add password protection for settings page
ArkEcosystem/desktop-wallet pull request #2939
Opened 2020-10-06 13:57 UTC by goga-m

## Summary
Require password input modal  from profiles that are password protected when navigating to settings page from navigation.

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [ ] Ready to be merged

2020-10-06 13:58 UTC, faustbrian commented
Task linked: [CU-8wt5th Profiles that are password protected shouldn't be allowed to get to settings page without inputting password (you can also get to other parts of wallets that way)](https://app.clickup.com/t/8wt5th)

2020-10-08 13:24 UTC, samharperpittam approved these changes

2020-10-08 14:48 UTC, samharperpittam requested changes
Seems I missed a conversation on this PR and additional work is still required. Retracting approval :D

2020-10-08 16:02 UTC, goga-m commented
Closing this in favor of https://github.com/ArkEcosystem/desktop-wallet/pull/2946
It is not necessary to require the password from setting menu, as the protected profile has already entered it in the `Welcome` screen.

2020-10-08 16:02 UTC, closed without merging