fix: limit networks with profile wallets
ArkEcosystem/desktop-wallet pull request #2950
Opened 2020-10-08 12:49 UTC by clucasalcantara

## Summary

Solves: https://app.clickup.com/t/90q0t1

- While sending money, limit the available networks to the profile wallet coins

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [ ] Ready to be merged

2020-10-12 09:55 UTC, samharperpittam approved these changes

2020-10-12 09:58 UTC, samharperpittam requested changes
@clucasalcantara - Can this change also be applied to the 'My Votes' and 'Registration' pages. So the user can only select  cryptoasset that belongs to their profile to register or vote with please?

2020-10-13 12:47 UTC, faustbrian approved these changes

2020-10-13 15:45 UTC, clucasalcantara commented
> @clucasalcantara - Can this change also be applied to the 'My Votes' and 'Registration' pages. So the user can only select cryptoasset that belongs to their profile to register or vote with please?

@samharperpittam updated, "My Votes" page (from navbar) and send registration page with networks filtered (only cryptoassets available in the user profile)

2020-10-15 23:21 UTC, luciorubeens approved these changes

2020-10-16 01:57 UTC, merged