refactor: misleading exit
ArkEcosystem/desktop-wallet pull request #3060
Opened 2020-11-03 14:39 UTC by clucasalcantara

## Summary

- [x] Refactor `Exit` to `Sign Out`
- [x] Adds an exit action to quit electron app

## Checklist

- [ ] Documentation _(if necessary)_
- [x] Tests _(if necessary)_
- [x] Ready to be merged

2020-11-04 11:06 UTC, samharperpittam approved these changes

2020-11-04 12:16 UTC, luciorubeens requested changes

2020-11-04 12:16 UTC, luciorubeens commented on src/electron/index.js
> +		find("port", 3000).then(
These electron events do not seem to wait for promises. The `concurrently` package has a parameter that seems to handle this` --kill-others`, so add it into the `dev` script in the ` package.json` file.

2020-11-05 14:10 UTC, luciorubeens approved these changes

2020-11-05 14:13 UTC, merged