feat: add validations in profile create
ArkEcosystem/desktop-wallet pull request #3097
Opened 2020-11-16 18:15 UTC by goga-m

## Summary
- [x] Create validation hook for profile domain
- [x] Add password confirmation field in `CreateProfile`
- [x] Remove 'Sign in with MSQ' buttons

## Checklist

- [ ] Documentation _(if necessary)_
- [x] Tests _(if necessary)_
- [x] Ready to be merged

2020-11-16 18:15 UTC, faustbrian commented
Task linked: [CU-a8yb3t Add 'Confirm Password' to Profile Creation screen](https://app.clickup.com/t/a8yb3t)

2020-11-17 10:06 UTC, samharperpittam requested changes
Changes requested. Added comments to clickup.

2020-11-18 16:48 UTC, samharperpittam approved these changes

2020-11-18 17:07 UTC, luciorubeens approved these changes

2020-11-18 17:07 UTC, merged