refactor: import wallet tweaks
ArkEcosystem/desktop-wallet pull request #3098
Opened 2020-11-16 19:29 UTC by brenopolanski

## Summary

Task: https://app.clickup.com/t/a4yg52

- [x] Change 'Go to Wallet' button to 'Save & Finish'
- [x] Show balance on completed page

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [x] Ready to be merged

2020-11-17 09:54 UTC, samharperpittam requested changes
Minor change requested. Comments added to clickup.

2020-11-17 13:20 UTC, samharperpittam approved these changes

2020-11-18 10:49 UTC, luciorubeens commented
@brenopolanski E2E failing

2020-11-18 13:37 UTC, brenopolanski commented
> @brenopolanski E2E failing

done @luciorubeens :+1:

2020-11-18 15:54 UTC, luciorubeens approved these changes

2020-11-18 15:55 UTC, merged