feat: filter wallets based on profile setting
ArkEcosystem/desktop-wallet pull request #3119
Opened 2020-11-24 17:55 UTC by goga-m

## Summary

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [ ] Ready to be merged

2020-11-24 18:04 UTC, faustbrian commented
Task linked: [CU-aez6mh Development Network Setting Changes](https://app.clickup.com/t/aez6mh)

2020-11-26 12:54 UTC, samharperpittam requested changes
Change requested. Comments left on Clickup

2020-11-26 15:04 UTC, samharperpittam approved these changes

2020-11-27 16:03 UTC, luciorubeens approved these changes

2020-11-27 16:03 UTC, merged