feat: implement plugin filtering
ArkEcosystem/desktop-wallet pull request #3389
Opened 2021-02-23 12:00 UTC by goga-m

## Summary

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2021-02-23 12:01 UTC, faustbrian commented
Task linked: [CU-ck1v52 [Plugins] add search capability](https://app.clickup.com/t/ck1v52)

2021-02-23 15:54 UTC, samharperpittam requested changes
Comments left on the Clickup task.

2021-02-25 12:01 UTC, samharperpittam approved these changes

2021-03-02 09:11 UTC, ItsANameToo approved these changes

2021-03-02 09:11 UTC, merged