refactor: add cryptoasset step to send transfer from navbar
ArkEcosystem/desktop-wallet pull request #3453
Opened 2021-03-04 15:30 UTC by luciorubeens

## Summary

https://app.clickup.com/t/egzf73

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2021-03-10 11:38 UTC, samharperpittam requested changes
@luciorubeens - Quick note on this.

When selecting 'Send' from the navbar, I don't think it really makes sense to show all networks if no wallets have been added for them.

For example, if I add just 1 ark devnet wallet to my profile, when I select Send from the navbar there's little point in showing APN or other networks that I can't send from anyway as I haven't added a wallet for them. If that makes sense?

So in a scenario where my profile only has 1 devnet wallet, when I select 'Send' from navbar, the only network that should be available to select is devnet.

2021-03-11 16:46 UTC, samharperpittam commented
@luciorubeens  - I believe that the network selector on the Send form should also be disabled as described in the task when selecting sending from the Nav bar. Otherwise the user can select the network twice which isn't really the desired behaviour.

2021-03-15 15:20 UTC, luciorubeens commented
@samharperpittam fixed

2021-03-17 12:51 UTC, samharperpittam approved these changes

2021-03-17 15:06 UTC, ItsANameToo approved these changes

2021-03-17 15:25 UTC, merged