refactor: adjust multiple wallet import to new design
ArkEcosystem/desktop-wallet pull request #3465
Opened 2021-03-09 13:06 UTC by luciorubeens

## Summary

https://app.clickup.com/t/egzjza

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [x] Tests _(if necessary)_
-   [x] Ready to be merged

2021-03-10 10:27 UTC, samharperpittam requested changes
@luciorubeens 

There's a couple of issues i've noticed with this when comparing against the design.

- The padding between each Ledger address in the tables appears to be larger than the design

- The 'Name' icon is different to what is used in the designs

- The 'balance' should be a smaller font size

- [] Padding
- [] Icon
- [] Font Size of Balance

2021-03-10 19:12 UTC, luciorubeens commented
@samharperpittam fixed

2021-03-11 16:32 UTC, samharperpittam commented
> @samharperpittam fixed

Looks great, thanks!

2021-03-11 16:33 UTC, samharperpittam approved these changes

2021-03-11 19:45 UTC, ItsANameToo approved these changes

2021-03-11 19:46 UTC, merged